channels:
- conda-forge
dependencies:
- python=3.12.5
- pip<=25.2
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==6.0.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
